# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-06 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=200)),
                ('when', models.CharField(max_length=200)),
                ('where', models.CharField(max_length=200)),
            ],
        ),
    ]
